### PR TITLE
Mix commonjs es6

### PR DESCRIPTION
**Pull request by ricardoribas**
### CHANGELOG
1 - Removed mixed exports (named exports for all methods and export default with all features)
2 - Recreated RN example project

### Observations
The main idea of this PR is to fix problems with RNWeb in which webpack have troubles resolving mixed commonJS and ES6 exports

### CODE REVIEW

**Comment by karimcambridge** [comment]
Was it really worth it to add prettier?

**Comment by ricardoribas** [comment]
Well, code linting and formatting is always good for people to understand the code. For this particular case it brought no value as the problem is not related with that. However is a small improvement for the next ones. I believe that there are deprecated methods that can be removed and the RN version can also be increased. What do you think ?

**Comment by bell-steven** [comment]
Hey @ricardoribas thank for the PR!

It looks like item number 1 on your list is already covered by #439.

The example project definitely can use updating, so thank you for working on it. I am having a hard time going through the PR because of all the prettier changes.  Would you mind reverting them for now?  It would make reviewing this PR a whole lot easier.  

Feel free to re-add it in a separate PR if you wish.

**Comment by bell-steven** [comment]
Hey, just a heads up, I ended up merging #514 into the `web-support` branch.

**Pull request closed without merging**
