### PR TITLE
feat: add ForwardRefExoticComponent types

### PR DESCRIPTION
**Pull request by strdr4605**
image

### CODE REVIEW

**Comment by bell-steven** [comment]
I can't thank you enough! I am going to try and post a preview release of v2 tonight.

**Comment by bell-steven** [comment]
@strdr4605 Can you point me in the right direction here? It doesn't seem to be working for me.
```js
const App = () => {
  const ref = useRef();

  useEffect(() => {
   ref.current?.setAddressText('Some Text')
  }, []);

  return (
    <View style={styles.container}>
      <GooglePlacesAutocomplete
        ref={ref}
        onPress={(data, details) => {}}
        query={{
          key: GOOGLE_PLACES_API_KEY,
          language: "en",
        }}
        placeholder="Search"
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: Constants.statusBarHeight,
    backgroundColor: "#ecf0f1",
    // backgroundColor: "black",
    padding: 8,
  },
});

export default App;
```

image

**Comment by strdr4605** [comment]
@bell-steven I checked in a TS file. See 
> [How to use TypeScript with React](https://www.educative.io/blog/react-and-typescript#how). 4. Strongly-typed refs in function components

In the TS file to get a proper typing is needed to annotate the `useRef`.

```ts
// App.tsx
import {
  GooglePlacesAutocompleteRef,
  GooglePlacesAutocomplete,
} from 'react-native-google-places-autocomplete';

const App = () => {
  const myRef = React.useRef<GooglePlacesAutocompleteRef>(null);

  React.useEffect(() => {
    myRef.current?.
  }, []);

  return (
    <>
      <GooglePlacesAutocomplete
        ref={myRef}
        placeholder={''}
        preProcess={(test) => test}
        query={{
          // available options: https://developers.google.com/places/web-service/autocomplete
          key: 'YOUR API KEY',
          language: 'en', // language of the results
          types: '(cities)', // default: 'geocode'
        }}
      />
```

-------------------

In your case `const ref = useRef();`, `ref` is inferred as `React.RefObject<undefined>`.

To the `<GooglePlacesAutocomplete ref={myRef} />` you can pass

image

**So in the end type for `myRef` is inferred as `React.RefObject<undefined>`. No suggestions 😢  !!!**

If you want strong typing in JS file:

```js
// App.jsx
const App = () => {
  /**
   * @typedef {import('react-native-google-places-autocomplete').GooglePlacesAutocompleteRef}
   */
  /**
   * @typedef {import('react').MutableRefObject}
   */

  /**
   * @type {React.MutableRefObject<GooglePlacesAutocompleteRef | null>}
   */
  const myRef = React.useRef(null);

  React.useEffect(() => {
    myRef.current?.getAddressText();
  }, []);

  return (
    <>
      <GooglePlacesAutocomplete
        ref={myRef}
        placeholder={''}
        preProcess={(test) => test}
        query={{
          // available options: https://developers.google.com/places/web-service/autocomplete
          key: 'YOUR API KEY',
          language: 'en', // language of the results
          types: '(cities)', // default: 'geocode'
        }}
      />
```
image

**Comment by bell-steven** [comment]
Gotcha.  Thank you for the detailed explanation.  I haven't jumped on to the typescript train yet, so this is unfamiliar waters to me.

**Comment by strdr4605** [comment]
To be honest I didn't know these things yesterday 😄 . Just investigated it today and learned something new. Spent an hour or two to figure out.

**Pull request merged**
