### PR TITLE
remove deprecated react lifecycles

### LINKED ISSUE #440: componentWillReceiveProps and componentWillMount are deprecate
Hi, I am working with this lib in version: 1.3.9 and react native in version 0.60.4 and at component initialization opens a few dialog boxes stating that the above components are obsolete.

### PR DESCRIPTION
**Pull request by bell-steven**
componentWillReceiveProps and componentWillMount are being deprecated.

I moved the debounce from componentWillMount to componentDidMount.

I also changed the componentWillReceiveProps lifecycle to componentDidUpdate.

Should close #440.

### CODE REVIEW

**Comment by VictorParraCant** [comment]
When implementing this change, it generates a fault in the `componentDidUpdate` by maximum update depth exceeded.

Attached error image: 

Screenshot_1572460463

**Comment by rodrigorz** [comment]
Fixed the "Maximum update depth exceeded" with an IF to compare pervious text and current text:

componentDidUpdate(prevProps) {
    if (prevProps.text == this.props.text) {
      return
    }
    ...rest of the code
}

**Comment by diegorodriguesvieira** [comment]
@FaridSafi any news about this?

**Comment by ste-hibo** [comment]
any news?

**Comment by bell-steven** [comment]
I am closing this for now.

#500 was merged, and will silence the error for now. 

I want to write the library with hooks, so we will be moving over to useEffect anyways.

**Pull request closed without merging**
