### PR TITLE
Add activity indicator when searching for places

### PR DESCRIPTION
**Pull request by oliveroneill**
This adds an ActivityIndicator displayed while the component searching for the latest query in the search bar. This avoids confusion on slow connections when a user inputs a location and there's no feedback.

### CODE REVIEW

**Comment by guilhermepontes** [comment]
Thank you @oliveroneill! I will soon publish it.

**Comment by guilhermepontes** [comment]
Another thing, would be nice to have a prop that we can set which component we want to use as loading. 
What do you think?

**Comment by oliveroneill** [comment]
Is that so that a user can have a custom loading screen?

**Comment by guilhermepontes** [comment]
Yep, I think would be a nice feature :)

**Comment by oliveroneill** [comment]
I guess so. It should be a pretty minor change. Should I make the changes on this pull request?

**Comment by guilhermepontes** [comment]
yep, sounds good :)

**Comment by oliveroneill** [comment]
@guilhermepontes Committed. Let me know what you think

**Comment by guilhermepontes** [comment]
Good job!

**Comment by Komeyl94** [comment]
how can I use this?

**Pull request merged**
