### PR TITLE
Add TypeScript definitions (.d.ts) file

### PR DESCRIPTION
**Pull request by acro5piano**
Hi, thank you for the great library.

It is helpful if there is type definitions file (`.d.ts`) for TypeScript user (like me).
I tried `npm install @types/react-native-google-places-autocomplete`, but unfortunately there are no type definitions in DefinitelyTyped.

Thank you.

### CODE REVIEW

**Comment by danbockapps** [comment]
This is fantastic but it needs `suppressDefaultStyles: boolean` added to the `GooglePlacesAutocompleteProps` interface.

**Comment by acro5piano** [comment]
@danbockapps 
Thank you, I added it.

It seems that the author of this library haven't maintained since four months, so we should create a PR for DefinitelyTyped instead.

**Comment by elgambet** [comment]
Thanks @danbockapps for the .d.ts file.

It would be nice if your PR merged.

**Comment by ataravati** [comment]
@acro5piano How can I use this in my project without having to wait for the PR to merge?

**Comment by acro5piano** [comment]
@ataravati 

I've added this file to my project as `myproject/typings/react-native-google-places-autocomplete.d.ts`.

**Comment by ataravati** [comment]
> @ataravati
> 
> I've added this file to my project as `myproject/typings/react-native-google-places-autocomplete.d.ts`.

Thank you! That didn't work for me. I got it working by wrapping the entire content of the file inside `declare module 'react-native-google-places-autocomplete' {}`.

**Comment by bell-steven** [comment]
Just tested this. Looks great.  This is extremely comprehensive.  We have to make sure we do a good job of keeping it up to date.
Closes #523 and #527.

Thanks @acro5piano!

**Comment by acro5piano** [comment]
Thank you for merging!

**Comment by bell-steven** [comment]
@acro5piano glad to get this out there. Thank you!

Live in v1.4.2

**Pull request merged**
