### PR TITLE
Setted default types to all

### PR DESCRIPTION
**Pull request by delvedor**
Hello!

According to the [google api](https://developers.google.com/places/web-service/autocomplete):
> The types of place results to return. See Place Types below. If no type is specified, all types will be returned.

This pr removes the `'geocode'` in default *query* to enable the *all types*.

Cheers.

### CODE REVIEW

**Comment by myaskevich** [comment]
Hi @delvedor 

`types: 'geocode',` is the default people got used to.

If you need `all`, why don't you just specify so in-place?

Am I missing something?

**Comment by delvedor** [comment]
Hi @myaskevich!
The google apis does not have an `'all'` parameter, if I want all the types at the same time, I must not specify it.
Maybe I misunderstood the documentation, there is another way to do it? :)

**Comment by delvedor** [comment]
Hi! Any news on this? :)

**Comment by delvedor** [comment]
Knock Knock! :P

**Comment by guilhermepontes** [comment]
@delvedor hey man! Sorry for the <s>huge</s> delay. Can you solve the conflicts so I can merge it?

**Comment by delvedor** [comment]
@guilhermepontes done, tell me if I did something wrong :)

**Comment by guilhermepontes** [comment]
Hello @delvedor, I'm really sorry for making you code this. The usage of `getDefaultProps()` is only for non-ES6 code and we are currently using ES6 on our lib. You can find more info [here](https://facebook.github.io/react/docs/react-without-es6.html).

Another point is that we already have the `defaultProps` in the code. As you can see [here](https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/master/GooglePlacesAutocomplete.js#L752).

I'll have to close this PR. :( 
Anyway, thank you for helping! 👍

**Pull request closed without merging**
