### PR TITLE
compatibility with webpack (for RNW)

### PR DESCRIPTION
**Pull request by alonp99**
This PR fixes compatibility issue with react-native-web (or webpack in general)

reference:
(https://stackoverflow.com/questions/42449999/webpack-import-module-exports-in-the-same-module-caused-error)

### CODE REVIEW

**Comment by bell-steven** [comment]
Hey @alonp99 thanks for the PR!

It looks like this PR tackles a couple of things. 

The issue in the title seems like it might be covered by #439.  

Can you share what other problems you are trying to solve with this PR?

**Comment by hthillman** [comment]
The url prop here is awesome.

I would add that the export issue can be solved by a babel plugin, although this may not be helpful for people trying to get spun up quickly:

```plugins: [
      ["@babel/plugin-transform-modules-commonjs", {
        "allowTopLevelThis": true
      }]
    ]```

**Comment by bell-steven** [comment]
I _think_ that the export syntax is compatible with RN all the way back, so I am going to merge it in.

**Comment by bell-steven** [comment]
I also think I might call the prop 'remoteUrl' or 'requestUrl'.  I think it makes it more clear.  What do you think?

Also, I think that the prop will be an object.  Something like this: 
```
{
    requestUrl: 'url',
    platformUse: 'web',
    platformUse: 'all',
}

**Pull request merged**
