### PR TITLE
Fix vulnerability of peer dependency

### PR DESCRIPTION
**Pull request by jhalborg**
Fixes https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/504

https://www.npmjs.com/advisories/1469

### CODE REVIEW

**Comment by xlogix** [comment]
Can it be updated to the latest version?

**Comment by jhalborg** [comment]
@xlogix - Can what be updated to what version? Not sure what you mean :-)

**Comment by xlogix** [comment]
I mean upgrading 'qs' to the latest version.

**Comment by jhalborg** [comment]
Done @xlogix

**Comment by Nnoerregaard** [comment]
@xlogix what's the status on merging this PR?

**Comment by jhalborg** [comment]
Quick fix while we wait for the merge (@mhreid ) :

`"react-native-google-places-autocomplete": "FaridSafi/react-native-google-places-autocomplete#505/head",`

**Comment by mhreid** [comment]
> Quick fix while we wait for the merge (@mhreid ) :
> 
> `"react-native-google-places-autocomplete": "FaridSafi/react-native-google-places-autocomplete#505/head",`

I had no idea you could do this! However, I had to do this to get it to work: `"react-native-google-places-autocomplete": "github:faridsafi/react-native-google-places-autocomplete#pull/505/head"`

**Comment by AntoinedeChassey** [comment]
@FaridSafi, @mayask, @guilhermepontes please merge this PR! :)

**Comment by FaridSafi** [comment]
Hello guys, I am looking for maintainers for this package. Is someone interested ?

**Comment by franxifra** [comment]
> "react-native-google-places-autocomplete": "github:faridsafi/react-native-google-places-autocomplete#pull/505/head"

Thanks for the tip! this line goes after import from or we actually have to install pull in npm?

Thank you

**Comment by xlogix** [comment]
@FaridSafi Interested

**Comment by bell-steven** [comment]
@guilhermepontes Is there anything stopping this from being merged?  I tested it locally and everything seems fine to me.  

I can merge this, but I don't have NPM access, so I wouldn't be able to publish a new release.

**Pull request merged**
