### PR TITLE
Fix for dynamic country change for search results restriction

### PR DESCRIPTION
**Pull request by salilgupta2510**
Hey, 
Is it possible for any one of you to look into this on priority.
I am working on a project which may stand gated because of this bug. 
If you have any other solution to this, then please suggest me.

Regards
Salil

### CODE REVIEW

**Comment by bell-steven** [comment]
Thank you for the PR.
If you need something urgently, please use [`patch-package`](https://github.com/ds300/patch-package). Please be mindful that his is open-source software.

**Comment by salilgupta2510** [comment]
@bell-steven Thanks for the insight, I will keep this in mind going forward.
As this is the first time I raised a PR to a public repo, could you help me in case anything is to be done differently here.

**Comment by bell-steven** [comment]
@nvojnovic would you be able to take a look at this?  I'm trying to figure out if this would cause too many re-renders.

**Comment by salilgupta2510** [comment]
We can also restrict the reconciliation to **props.query**.

**Comment by nvojnovic** [comment]
> @nvojnovic would you be able to take a look at this? I'm trying to figure out if this would cause too many re-renders.

It would not cause too many re-renders because props change already causes re-render but useMemo would not make much sense with just props object in dependency array.
However there are two possible solutions:

1.) future-proof, easy to read and understand
```
// wrap _request in useCallback and put changeable props used by _request in dependency array
const _request = useCallback((text) => {
  _abortRequests();
  ...rest of function code
}, [props.minLength, props.timeout, props.onTimeout, props.query, ...]);

// then just add _request in dependency array of debounceData memo
// also can put props.debounce if it's considered as changeable
const debounceData = useMemo(() => debounce(_request, props.debounce), [_request]);
```
2.) @salilgupta2510 proposal that will fix just this issue
```
// just add props.query in dependency array of debounceData
const debounceData = useMemo(() => debounce(_request, props.debounce), [props.query]);
```

**Comment by bell-steven** [comment]
Thanks for the PR.
Closed in favor of #703

**Pull request closed without merging**
