### PR TITLE
Add ability to change the underlay color of the result list

### PR DESCRIPTION
**Pull request by aniruddhashevle**
Thanks for the amazing package, It is working perfectly but I think there is minor improvment need to be incorporated. While implementing I realize that you have specified a particular underlay color for the result list rows. It's better to make it dynamic so in this pull request I have added provision to pass underlay color  as a prop named **listUnderlayColor** and if user does not provide this prop then by default underlay color ("#c8c7cc") will get applied.

Let me know if any queries.

### CODE REVIEW

**Comment by aniruddhashevle** [comment]
Thanks @myaskevich. I've added **listUnderlayColor prop validation**.

**Comment by kmanishprdxn** [comment]
@myaskevich @FaridSafi I'm also facing similar problem and changes mentioned in this pull request will resolve those problems. Can you please update us regarding when you can incorporate this changes or any plans for next release. So that I'll update my npm package accordingly.

**Comment by myaskevich** [comment]
Thanks @aniruddhashevle

**Comment by myaskevich** [comment]
@kmanishprdxn @aniruddhashevle  v1.2.8 published to npm

**Comment by kmanishprdxn** [comment]
@myaskevich Thanks

**Pull request merged**
