### PR TITLE
Fix onChangeText

### PR DESCRIPTION
**Pull request by jgking2**
Pull the onChangeText through the spread, similar to onBlur / onFocus.

### CODE REVIEW

**Comment by jgking2** [comment]
@bell-steven would you mind reviewing / merging this one?

**Comment by bell-steven** [comment]
@jgking2 what are you trying to solve with this PR?

**Comment by jgking2** [comment]
@bell-steven that would definitely be helpful haha.  So you'll notice that the `onChangeText` event is mapped to `_handleChangeText`, but then the props are spread at the end.  So basically, if you add `onChangeText`, you'll override the entire auto complete functionality (none of the events will fire).  This pulls it out, so the spread won't overwrite it.

There's also a weird thing with the `onChangeText` firing immediately with an empty string, but that is probably for a reason, and we can work around that!

**Comment by bell-steven** [comment]
Thanks for that. Is this supposed to be a direct fix for #632?

**Comment by jgking2** [comment]
Absolutely, I encountered it myself but it's explained great there!

**Review by bell-steven — APPROVED** [review]

**Pull request merged**
