### PR TITLE
Update react

### PR DESCRIPTION
**Pull request by esganzerla**
This PR is updating a few things about react, some are already presenting warnings:

1. `isMounted()` is deprecated as mentioned on issue #162.
2. `react.createClass()` is deprecated as mentioned on issue #154.
3. `React.PropTypes` will soon be deprecated as mentioned by Facebook (https://facebook.github.io/react/warnings/dont-call-proptypes.html) and should be imported as `prop-types`.
4. `TouchableWithoutFeedback` was being imported and not used.
5. `GooglePlacesAutocomplete` now is exported as Default and as a component.

### CODE REVIEW

**Comment by dieguitoweb** [comment]
@FaridSafi Do you need any help for merge this PR?

**Comment by jackdcrawford** [comment]
Would be great to get this into the next release, currently incompatible with react-native 0.47 due to the breaking changes in React 16.

**Comment by guilhermepontes** [comment]
Thank you @esganzerla :)

**Comment by poptocrack** [comment]
Thank's for this update, feels good to not have any red lines in console anymore

**Pull request merged**
