### PR TITLE
Update react with flatlist

### PR DESCRIPTION
**Pull request by esganzerla**
This changes `ListView` to `FlatList` (as mentioned in issue #175), still takes styles as a `props.styles.listView` to keep compatibility.

**NOTE:** This has also updates react as in PR #181 .

### CODE REVIEW

**Comment by zolrath** [comment]
I believe ` {this._getListView()}` on line 699 should be `{this._getFlatList()}`
Once this change is made it shows further errors as `this.state.dataSource.cloneWithRows` is undefined.

**Comment by esganzerla** [comment]
Oops, I probably forgot to push some commit, I tested it here. I will check it later today or tomorrow.

**Comment by esganzerla** [comment]
should be fine now

**Comment by kelset** [comment]
@FaridSafi @jamesone any update on merging this PR? ( + #181 + #178 ?)

**Comment by esganzerla** [comment]
@kelset actually I did update is mounted() issue on #181 too and some others react updates.

**Comment by kelset** [comment]
Oh nice to hear, but still basically this one and #181 are "complementary", right? Meaning, both would need to be merged to get everything working properly right?

**Comment by guilhermepontes** [comment]
Thank you guys! :)

**Comment by guilhermepontes** [comment]
Available on `1.3.0`

**Pull request merged**
