### PR TITLE
use custom styles to fix view development error

### PR DESCRIPTION
**Pull request by danReynolds**
the `styles` prop creates errors in newer version of React-Native, ours is 0.48, since it eventually gets passed down to a view which errors because of this: https://github.com/facebook/react-native/blob/f4d627c8faeb034eac8053fd253f17e42b85f2f2/Libraries/Renderer/ReactNativeRenderer-dev.js#L3659.

This naive solution just renames the prop to customStyles which fixes the issue but does not preserve backwards compatibility. This is what we're doing for us since that isn't an issue but feel free to make recommendations.

It also adds a dist directory with transpiled output for consumers that do not want to transpile their node modules.

### CODE REVIEW

**Comment by guilhermepontes** [comment]
Thank you so much for your PR @danReynolds. But, the PR #252 did the same and I just merged it, so I'll have to close this for now.

Don't be discouraged by this, I really hope you can contribute again! :love:

**Comment by danReynolds** [comment]
@guilhermepontes While his is similar, I think we still have this issue. If you don't suppress styles it will be using the styles prop you send down, which as I referenced in react-native code creates an error. Let me know if that makes sense!

**Comment by guilhermepontes** [comment]
I know what you meant.

**Comment by testshallpasswork** [comment]
@guilhermepontes Any workaround until this gets merged? _besides downgrade_

**Pull request closed without merging**
