### PR TITLE
fix(props.text) pass proper callback to setState

### PR DESCRIPTION
**Pull request by sapter**
### Fix
in `UNSAFE_componentWillReceiveProps`, `setState` expects a callback as its second argument -- not a `void | undefined`. This small change fixes it.

Signed-off-by: Sam Apter <sam.apter@brandingbrand.com>

### CODE REVIEW

**Comment by bell-steven** [comment]
`this._handleChangeText()` is function...  
What is this a fix for? What happened vs the expected behavior?

Unless I am fundamentally misunderstanding how all this works (I learned JS when promises became a thing). 
I played around with the setState call back, here is a [link to the stackblitz](https://stackblitz.com/edit/react-5ixbl9) I was using.

**Comment by sapter** [comment]
@bell-steven 
Yes, `_handleChangeText` is a function, but the way to pass that function to `setState` is just to give its name -- without invoking it (adding the `()` in the end). When you're passing an invoked function to `setState` you're actually passing the _return value_ of that function rather than the function itself. So if `_handleChangeText` didn't take a parameter the fix would be just that: the second argument to `setState` should be changed from `handleChangeText()` to `handleChangeText`. But because it **does** take a parameter, that won't do it. So you need to change it instead to `() => this._handleChangeText(nextProps.text)`. This way, you're still passing a function rather than its return value to `setState` and you're also specifying what argument to feed the function's parameter.

As to your stackpblitz, go ahead and try it again. The value you see logged by the `console.log` is off by one digit from the value in the counter on the screen. That's because the function is invoked right away rather than passing just the name of the function to be invoked by `setState` when it's done updating the state. Change `this.checkAge()` to `this.checkAge` or to `() => this.checkAge()` and look at the log and you'll see that now it matches what's in the counter on the page.

**Comment by bell-steven** [comment]
@sapter thanks for that.  Thats what I was thinking in the back of mind. I really appreciate the detailed explanation!

p.s. while I have you here, would you be able to shed some light on #558?

**Comment by sapter** [comment]
@bell-steven  I'll have a look at it in the morning. I already closed my computer for the night.

**Comment by bell-steven** [comment]
Thanks!

**Pull request merged**
