### PR TITLE
Using ActivityIndicator instead of deprecated ActivityIndicatorIOS

### PR DESCRIPTION
**Pull request by grabcode**

### CODE REVIEW

**Comment by myaskevich** [comment]
Hi @grabcode 

Thanks for the PR.

One question, does it play well with the previous versions of RN?

**Comment by grabcode** [comment]
No, it doesn't work with older versions. People needs to upgrade to react-native 0.28 minimum.

**Comment by grabcode** [comment]
@myaskevich are you thinking to merge? I reckon given the react-native update rate, it's not necessary to make the code retro-compatible. Best would be to tag the releases, and leave a comment in the README.md.

**Comment by myaskevich** [comment]
@grabcode Can you update README please and I'll merge it right away

**Comment by grabcode** [comment]
@myaskevich done

**Comment by myaskevich** [comment]
@grabcode available on npm

**Pull request merged**
