### PR TITLE
Scrollable row for long items & use renderSeparator

### PR DESCRIPTION
**Pull request by magrinj**
I just change the row, to allow them to be scrollable, because sometimes you got long addresses, in the result and you can't really choose the right one because the Text is cut.
I also move the separator view in the `renderSeparator` function of the ListView.

### CODE REVIEW

**Comment by myaskevich** [comment]
Hi @magrinj 

Thanks for the PR.

One thing I'm not quite sure about is how it'll look like.
Could you please attach a small Gif/Video showing it in action please?

Thanks
Max

**Comment by magrinj** [comment]
Hi @myaskevich,

Of course, sorry for the delay:

exemple

**Comment by myaskevich** [comment]
Thanks @magrinj !

Could you please rebase it against master and I'll merge it in.

Max

**Comment by magrinj** [comment]
@myaskevich Sorry for the delay, I solve the conflict and do a small fix

**Comment by myaskevich** [comment]
Thanks!

**Comment by magrinj** [comment]
Your welcome :)

**Comment by tvn19113** [comment]
Hi @magrinj , It seems did not work with Android

**Pull request merged**
