### PR TITLE
componentWillMount -> UNSAFE_componentWillMount

### PR DESCRIPTION
**Pull request by strdr4605**

### CODE REVIEW

**Comment by strdr4605** [comment]
@guilhermepontes when the new version of the npm package will be released?

**Comment by guilhermepontes** [comment]
@strdr4605 I will deploy this new version tonight. I'm working a new version of this package from scratch that's why is not being updated constantly, the code is too old to refactor.

**Comment by strdr4605** [comment]
> I'm working a new version of this package from scratch that's why is not being updated constantly, the code is too old to refactor.

Maybe you can open and ROADMAP issue (Or. multiple issues) with all the things that should be implemented and maybe someone will help.

**Comment by guilhermepontes** [comment]
Good idea, will do it. Thanks!

**Pull request merged**
