### PR TITLE
Update GooglePlacesAutocomplete.d.ts

### PR DESCRIPTION
**Pull request by bill-pairaktaridis**
Adding definition for `renderRow`

### CODE REVIEW

**Review by bell-steven — APPROVED** [review]

**Comment by bell-steven** [comment]
Thanks for the PR! I will test and merge next week hopefully.

**Comment by bell-steven** [comment]
Published as v1.9.0

**Comment by bell-steven** [comment]
Would you be able to help out with a typescript definition in #625?

**Comment by bill-pairaktaridis** [comment]
@bell-steven I can take a look but I'm not extremely versed in TS. Is there something specific you'd like me to help out with?

**Comment by bell-steven** [comment]
I'm looking for help writing one specific definition. See #625

**Pull request merged**
